version: '3.7'
services:
  api:
    image: lykinsbd/asa_to_fdm:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - redis
      - worker
  redis:
    image: redis:4.0.11-alpine
  worker:
    image: lykinsbd/asa_to_fdm:latest
    command: python3 worker.py
    depends_on:
      - redis